package com.operativ_tarsulat;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Agent.java
//  @ Date : 2022. 03. 19.
//  @ Author : 
//
//




public abstract class Agent implements Steppable, Effect {
    public int Duration;
    private Virologist virologist;
    public void DecreaseDuration() {
    	throw new RuntimeException("Unimplemented");
    }
    
    public void Step() {
    	throw new RuntimeException("Unimplemented");
    }
}
