package com.operativ_tarsulat;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Building.java
//  @ Date : 2022. 03. 19.
//  @ Author : 
//
//




public interface Building  {
    public void Interact(Virologist v);
}
