package com.operativ_tarsulat;

import java.util.List;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : City.java
//  @ Date : 2022. 03. 19.
//  @ Author : 
//
//




public class City extends Field {
    private List<Building> buildings;
    public City(List<Building> buildings)
    {
    	this.buildings = buildings;
    }
    public City() {}
    public List<Building> GetBuildings() {
    	return buildings;
    }
    
    public void Interact(Virologist v) {
    	for(int i = 0;i<buildings.size();i++)
    	{
    		buildings.get(i).Interact(v);
    	}
    }
    public void AddBuilding(Building b) {
    	buildings.add(b);
    }
}
