package com.operativ_tarsulat;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : City.java
//  @ Date : 2022. 03. 19.
//  @ Author : 
//
//




public class City extends Field {
    private Building buildings;
    public Building[] GetBuildings() {
    	return null;
    }
    
    public void Interact(Virologist v) {
    	throw new RuntimeException("Unimplemented");
    }
    
    public void AddBuilding(Building b) {
    	throw new RuntimeException("Unimplemented");
    }
}
