package com.operativ_tarsulat;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DanceVirus.java
//  @ Date : 2022. 03. 19.
//  @ Author : 
//
//




public class DanceVirus extends Agent {
    public Boolean HandleTouch(Virologist v, Agent i, Virologist v2) {
    	throw new RuntimeException("Unimplemented");
    }
    
    public Boolean HandleMove(Virologist v) {
    	throw new RuntimeException("Unimplemented");
    }
    
    public int HandleInventoryCapacity(Virologist v) {
    	throw new RuntimeException("Unimplemented");
    }
    
    public Boolean HandleParalyzed(Virologist v) {
    	throw new RuntimeException("Unimplemented");
    }
    
    public Boolean HandleCreateAgent(Virologist v, GeneticCode code) {
    	throw new RuntimeException("Unimplemented");
    }
    
    public void HandleTurnStart(Virologist v) {
    	throw new RuntimeException("Unimplemented");
    }
}
