package com.operativ_tarsulat;

import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Field.java
//  @ Date : 2022. 03. 19.
//  @ Author : 
//
//




public abstract class Field {
    private LinkedList<Virologist> virologists;
    private List<Field> neighbours;
    public Gear droppedGear;
    /**
     * The constructor of the Field class.
     * @param g The Gear
     * @param neigh
     * @param virologists
     */
    
    public Field() {
    	Skeleton.LogFunctionCall("Field ctr");
    	neighbours = new LinkedList<Field>();
    	virologists = new LinkedList<Virologist>();
    	Skeleton.LogReturn();
    }
    
	public void Accept(Virologist v) {
    	Skeleton.LogFunctionCall(new Object() {}.getClass().getEnclosingMethod().getName(),v.getName(),v.getClass().getName());
    	virologists.add(v);
    	Skeleton.LogReturn();
    }
    
    public Boolean Remove(Virologist v, Field f) {
    	Skeleton.LogFunctionCall(new Object() {}.getClass().getEnclosingMethod().getName(),v.getName(),f.getClass().getName(),v.getClass().getName());
    	if(neighbours.contains(f))
    	{
    		virologists.remove(v);
    		Skeleton.LogReturn("true");
    		return true;
    	}
    	Skeleton.LogReturn("false");
    	return false;
    		
    }
    
    public abstract void Interact(Virologist v);
    
    public List<Field> GetNeighbours() {
    	Skeleton.LogFunctionCall(new Object() {}.getClass().getEnclosingMethod().getName());
    	Skeleton.LogReturn(neighbours.toString());
    	return neighbours;
    }
    
    public void AddNeighbour(Field f) {
    	Skeleton.LogFunctionCall(new Object() {}.getClass().getEnclosingMethod().getName());
    	Skeleton.LogReturn();
    	neighbours.add(f);
    }
}
