package com.operativ_tarsulat;

import java.util.ArrayList;
import java.util.List;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Field.java
//  @ Date : 2022. 03. 19.
//  @ Author : 
//
//




public abstract class Field {
    private ArrayList<Virologist> virologists;
    private List<Field> neighbours;
    public Gear droppedGear;
    public Field(Gear g,List<Field> neigh,ArrayList<Virologist> virologists)
    {
    	Skeleton.LogFunctionCall(new Object() {}.getClass().getEnclosingMethod().getName(),virologists.getClass().getName(),neigh.getClass().getName(),g.getClass().getName());
    	droppedGear = g;
    	neighbours = neigh;
    	this.virologists  = virologists;
    	Skeleton.LogReturn();
    }
    public Field() {}
	public void Accept(Virologist v) {
    	Skeleton.LogFunctionCall(new Object() {}.getClass().getEnclosingMethod().getName(),v.getName(),v.getClass().getName());
    	virologists.add(v);
    	Skeleton.LogReturn();
    }
    
    public Boolean Remove(Virologist v, Field f) {
    	Skeleton.LogFunctionCall(new Object() {}.getClass().getEnclosingMethod().getName(),v.getName(),f.getClass().getName(),v.getClass().getName());
    	if(neighbours.contains(f))
    	{
    		virologists.remove(v);
    		Skeleton.LogReturn("true");
    		return true;
    	}
    	Skeleton.LogReturn("false");
    	return false;
    		
    }
    
    public abstract void Interact(Virologist v);
    
    public List<Field> GetNeighbours() {
    	Skeleton.LogFunctionCall(new Object() {}.getClass().getEnclosingMethod().getName());
    	Skeleton.LogReturn(neighbours.toString());
    	return neighbours;
    }
    
    public void AddNeighbour(Field f) {
    	Skeleton.LogFunctionCall(new Object() {}.getClass().getEnclosingMethod().getName());
    	Skeleton.LogReturn();
    	neighbours.add(f);
    }
}
