package com.operativ_tarsulat;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Field.java
//  @ Date : 2022. 03. 19.
//  @ Author : 
//
//




public abstract class Field {
    private Virologist virologists;
    private Field neighbours;
    public Gear droppedGear;
    public void Accept(Virologist v) {
    }
    
    public Boolean Remove(Virologist v, Field f) {
    	throw new RuntimeException("Unimplemented");
    }
    
    public abstract void Interact(Virologist v);
    
    public Field[] GetNeighbours() {
    	throw new RuntimeException("Unimplemented");
    }
    
    public void AddNeighbour(Field f) {
    	throw new RuntimeException("Unimplemented");
    }
}
