package com.operativ_tarsulat;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FreeField.java
//  @ Date : 2022. 03. 19.
//  @ Author : 
//
//




public class FreeField extends Field {
    public void Interact(Virologist v) {
    	throw new RuntimeException("Unimplemented");
    }
}
