package com.operativ_tarsulat;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FreeField.java
//  @ Date : 2022. 03. 19.
//  @ Author : 
//
//

import java.io.Serializable;

public class FreeField extends Field implements Serializable {
	
	public FreeField()
	{
		Skeleton.LogFunctionCall("FreeField ctr");
		Skeleton.LogReturn();
	}
    public void Interact(Virologist v) {
    }
}
