package com.operativ_tarsulat;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Game.java
//  @ Date : 2022. 03. 19.
//  @ Author : 
//
//




public class Game {
    private Virologist virologists;
    private Field fields;
    public void StartGame(String saveFile, int seed, String[] names) {
    }
    
    public void EndGame() {
    }
    
    public void NextTurn() {
    }
    
    public void LoadGame(String saveFile) {
    }
    
    public void SaveGame() {
    }
    
    public void ExitGame() {
    }
}
