package com.operativ_tarsulat;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : GeneticCode.java
//  @ Date : 2022. 03. 19.
//  @ Author : 
//
//




public abstract class GeneticCode {
    private Virologist wizards;
    public abstract Agent CreateInstance(Virologist v);
    public abstract int GetAminoCost();
    public abstract void CheckList(GeneticCodeCheckList ls);
    public abstract int GetNucleoCost();
}
