package com.operativ_tarsulat;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Shelter.java
//  @ Date : 2022. 03. 19.
//  @ Author : 
//
//




public class Shelter implements Building {
    private Gear localGear;
    public void Interact(Virologist v) {
    	throw new RuntimeException("Unimplemented");
    }
    
    public void SetGear(Gear g) {
    	throw new RuntimeException("Unimplemented");
    }
}
