package com.operativ_tarsulat;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Shelter.java
//  @ Date : 2022. 03. 19.
//  @ Author : 
//
//




public class Shelter implements Building {
    private Gear localGear;
    public Shelter(Gear localG)
    {
    	localGear = localG;
    }
    public Shelter() {}
    public void Interact(Virologist v) {
    	if(localGear!=null)
    	{
    		v.GetGear(localGear);
    	}
    	
    }
    
    public void SetGear(Gear g) {
    	localGear=g;
    }
}
