package com.operativ_tarsulat;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Steppable.java
//  @ Date : 2022. 03. 19.
//  @ Author : 
//
//




public interface Steppable {
    public void Step();
}
