package com.operativ_tarsulat;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Warehouse.java
//  @ Date : 2022. 03. 19.
//  @ Author : 
//
//




public class Warehouse implements Building {
	
	public void SetAmino(int amount) {
		throw new RuntimeException("Unimplemented");
	}
	
	public void SetNucleo(int amount) {
		throw new RuntimeException("Unimplemented");
	}
	
    public void Interact(Virologist v) {
    	throw new RuntimeException("Unimplemented");
    }
}
