package com.operativ_tarsulat;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Warehouse.java
//  @ Date : 2022. 03. 19.
//  @ Author : 
//
//




public class Warehouse implements Building {
	
	
	private int nucleo;
	private int amino;
	public Warehouse(int nuc,int am)
	{
		nucleo = nuc;
		amino = am;
	}
	public Warehouse() {}
	public void SetAmino(int amount) {
		amino = amount;
	}
	
	public void SetNucleo(int amount) {
		nucleo = amount;
	}
	
    public void Interact(Virologist v) {
    	Skeleton.LogFunctionCall(new Object() {}.getClass().getEnclosingMethod().getName(),v.getName(),v.getClass().getName());
    
    	int aminoNeed=v.GetVacantAmino();
    	int nucleoNeed=v.GetVacantNucleo();
    	v.GetMaterial(aminoNeed, nucleoNeed);
    	Skeleton.LogReturn();
    }
}
