//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Bag.java
//  @ Date : 2022. 03. 19.
//  @ Author : 
//
//




public class Bag extends Gear {
    private GearSlot slot;
    public Boolean HandleTouch(Virologist v, Agent i, Virologist v2) {
    }
    
    public Boolean HandleMove(Virologist v) {
    }
    
    public int HandleInventoryCapacity(Virologist v) {
    }
    
    public Boolean HandleParalized(Virologist v) {
    }
    
    public Boolean HandleCreateAgent(Virologist v, GeneticCode code) {
    }
    
    public void HandleTurnStart(Virologist v) {
    }
    
    public GearSlot GetSlot() {
    }
    
    public GearSlot GetSlot() {
    }
}
