//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Gear.java
//  @ Date : 2022. 03. 19.
//  @ Author : 
//
//




public abstract class Gear implements Effect {
    public abstract GearSlot GetSlot();
}
