//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : GeneticCodeCheckList.java
//  @ Date : 2022. 03. 19.
//  @ Author : 
//
//




public class GeneticCodeCheckList {
    public Boolean Protectione;
    public Boolean Amnesia;
    public Boolean Paralyzer;
    public Boolean Dance;
    private GeneticCode completeSpellList;
    public void CheckEndCondition() {
    }
}
