//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ParalyzeGeneticCode.java
//  @ Date : 2022. 03. 19.
//  @ Author : 
//
//




public class ParalyzeGeneticCode extends GeneticCode {
    public ParalyzeVirus CreateInstance(Virologist v) {
    }
    
    public int GetAminoCost() {
    }
    
    public void CheckList(GeneticCodeCheckList ls) {
    }
    
    public int GetNucleoCost() {
    }
    
    public Agent CreateInstance(Virologist v) {
    }
    
    public int GetAminoCost() {
    }
    
    public void CheckList(GeneticCodeCheckList ls) {
    }
    
    public int GetNucleoCost() {
    }
}
