//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Shelter.java
//  @ Date : 2022. 03. 19.
//  @ Author : 
//
//




public class Shelter extends Building, Field implements Building {
    private Gear localGear;
    public void Interact(Virologist v) {
    }
}
