//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Timer.java
//  @ Date : 2022. 03. 19.
//  @ Author : 
//
//




public class Timer {
    public void Tick() {
    }
    
    public void AddSteppable(Steppable s) {
    }
    
    public void RemoveSteppable(Steppable s) {
    }
}
