//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Virologist.java
//  @ Date : 2022. 03. 19.
//  @ Author : 
//
//




public class Virologist implements Steppable {
    private Field field;
    private GeneticCode learnedSpells;
    private Gear gear;
    public GeneticCode learnedSpells;
    private GeneticCode learnedGeneticCodes;
    private Agent activeSpells;
    private Agent activeAgents;
    private Agent agentInventory;
    public void UseAgent(Virologist v, Agent a) {
    }
    
    public void ReceiveAgentUse(Agent a, Virologist v) {
    }
    
    public void LearnGeneticCode(GeneticCode s) {
    }
    
    public Gear GetGear(Gear g) {
    }
    
    public void RemoveGear(Gear r) {
    }
    
    public void Move(Field f) {
    }
    
    public void Step() {
    }
    
    public void Steal(Virologist v, Gear r) {
    }
    
    public Boolean StolenFrom(Virologist v, Gear r) {
    }
    
    public Field GetField() {
    }
    
    public void InteractWithField() {
    }
    
    public void StealMaterials(Virologist v) {
    }
    
    public void StolenMaterialsFrom(Virologist v) {
    }
    
    public void GetMaterial(int amino, int nucleo) {
    }
    
    public int GetVacantAmino() {
    }
    
    public int GetVacantNucleo() {
    }
    
    public void CreateAgent(GeneticCode code) {
    }
    
    public void EndTurn() {
    }
    
    public void AddAgent(Agent a) {
    }
    
    public void RemoveAgent(Agent a) {
    }
}
