//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Warehouse.java
//  @ Date : 2022. 03. 19.
//  @ Author : 
//
//




public class Warehouse extends Building implements Building {
    public void Interact(Virologist v) {
    }
}
